services:
  frontend_app:
    build:
      context: ../../../src/frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: frontend_app
    ports:
      - "${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}"
    volumes:
      - ../../../src/frontend/src:/app/src
    restart: always
    env_file:
      - ../../../.env
      - ../../../.env.docker
    networks:
      - microservices_net_01
networks:
  microservices_net_01:
    external: true