services:
  frontend_app:
    build:
      context: ../../../services/frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: ${FRONTEND_CONTAINER_NAME}
    ports:
      - "${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}"
    volumes:
      - ../../../services/frontend/src:/app/src
    restart: always
    env_file:
      - ../../../.env
    networks:
      - microservices_net_01
networks:
  microservices_net_01:
    external: true