services:
  react_agent:
    build:
      context: ../../../services/agent/
      additional_contexts:
        packages: ../../../packages/
      dockerfile: Dockerfile
      target: development
    container_name: ${REACT_AGENT_CONTAINER_NAME}
    ports: 
      - "${REACT_AGENT_PORT}:${REACT_AGENT_PORT}"
    volumes:
      - ../../../services/agent/src:/app/src
    restart: always
    env_file:
      - ../../../.env
    networks:
      - mcp_net
      - data_net
      - microservices_net

networks:
  mcp_net:
    external: true

  data_net:
    external: true

  microservices_net:
    external: true