services:
  woahai_react_agent:
    build:
      context: ../../../src/ReactAgent/
      dockerfile: Dockerfile
      target: development
    container_name: WoahAIReactAgent
    ports: 
      - "${WOAHAI_LLM_AGENT_PORT}:${WOAHAI_LLM_AGENT_PORT}"
    volumes:
      - ../../../src/ReactAgent/src:/app/src
    restart: always
    env_file:
      - ../../../.env
      - ../../../.env.docker
    networks:
      - mcp_net
      - woahai_data_net
      - microservices_net

networks:
  mcp_net:
    external: true

  woahai_data_net:
    external: true

  microservices_net:
    external: true