
services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "${WOAH_NGINX_PROXY_PORT}:${WOAH_NGINX_PROXY_PORT}"
    volumes:
      - ../../../../src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../../../src/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../../../../src/nginx/proxy_params:/etc/nginx/proxy_params:ro