
services:
  mcp_gateway:
    build:
      context: ../../../services/mcp/gateway
      additional_contexts:
        packages: ../../../packages/
      dockerfile: Dockerfile
      target: development
    container_name: ${MCP_GATEWAY_CONTAINER_NAME}
    ports: 
      - "${MCP_GATEWAY_PORT}:${MCP_GATEWAY_PORT}"
    volumes:
      - ../../../services/mcp/gateway:/app/
    restart: always
    env_file:
      - ../../../.env
    networks:
      - mcp_net

  web_search_mcp:
    build:
      context: ../../../services/mcp/servers/web_search
      additional_contexts:
        packages: ../../../packages/
      dockerfile: Dockerfile
      target: development
    container_name: ${WEB_SEARCH_MCP_CONTAINER_NAME}
    ports:
      - "${WEB_SEARCH_MCP_PORT}:${WEB_SEARCH_MCP_PORT}"
    volumes:
      - ../../../services/mcp/servers/web_search/src:/app/src
    restart: always
    env_file:
      - ../../../.env
    networks:
      - mcp_net


networks:
  mcp_net:
    external: true