export const config = {
  NEXT_PUBLIC_AUTH_API_URI: process.env.NEXT_PUBLIC_AUTH_API_URI,
  NEXT_PUBLIC_USER_API_URI: process.env.NEXT_PUBLIC_USER_API_URI,
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  NEXT_PUBLIC_APP_PORT: process.env.NEXTJS_APP_PORT?.toString() || '3000',
};