// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

const localEnv = path.resolve(__dirname, "../../../.env");
const rootEnv = path.resolve(__dirname, "./.env");

if (fs.existsSync(localEnv)) {
  dotenv.config({ path: localEnv });
} else {
  dotenv.config({path: rootEnv});
}

export default defineConfig({
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["USERS_PRISMA_DB_URI"],
  },
});
