services:
  api_gateway:
    build:
      context: ../../src/ms/api_gateway/
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: api_gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    volumes:
      - ../../src/ms/api_gateway/:/app
      - ../../src/ms/api_gateway/routes.json:/app/routes.json
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_MAILER_SERVICE_PORT=${AUTH_MAILER_SERVICE_PORT}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - CAPTCHA_VERIFICATION_PORT=${CAPTCHA_VERIFICATION_PORT}
      - USER_CODE_VERIFICATION_PORT=${USER_CODE_VERIFICATION_PORT}
    networks:
      - microservices_net_01

networks:
  microservices_net_01:
    external: true