services:
  wohaai-agent:
    build:
      context: ../../../services/agent/
      dockerfile: ../../agent/Dockerfile
      target: ${NODE_ENV}
    container_name: ${AGENT_CONTAINER_NAME}
    ports: 
      - "${AI_AGENT_PORT}:${AI_AGENT_PORT}"
    volumes:
      - ../../:/app
    restart: always
    env_file:
      - ../../.env
    networks:
      - woahai_dev_net