services:
  frontend_app:
    build:
      context: ../../../services/frontend
      additional_contexts:
        packages: ../../../packages/
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: ${FRONTEND_CONTAINER_NAME}
    ports:
      - "${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}"
    volumes:
      - ../../../services/frontend/src:/app/src
    restart: always
    env_file:
      - ../../../.env
    networks:
      - woahai_dev_net


networks:
  woahai_dev_net:
    external: true