services:
  web-app:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
      target: ${NODE_ENV}
    container_name: ${NEXTJS_APP_CONTAINER_NAME}
    ports:
      - "${NEXTJS_APP_PORT}:3000"
    volumes:
      - ../../:/app
    restart: always
    env_file:
      - ../../.env
    networks:
      - WohaAI_dev_net
    profiles:
      - "apps"

networks:
  WohaAI_dev_net: