services:
  # ===========================
  # Users MongoDB
  # ===========================
  users-mongo-db:
    image: mongo:7
    container_name: ${USERS_MONGO_DB_NAME}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERS_MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${USERS_MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${USERS_MONGO_DB_DATABASE}
    ports:
      - "${USERS_MONGO_DB_PORT}:27017"
    volumes:
      - users_mongo_data:/data/db
    networks:
      - WohaAI_dev_net
    profiles:
      - "repo"

  # ===========================
  # Threads MongoDB
  # ===========================
  threads-mongo-db:
    image: mongo:7
    container_name: ${THREADS_MONGO_DB_NAME}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${THREADS_MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${THREADS_MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${THREADS_MONGO_DB_DATABASE}
    ports:
      - "${THREADS_MONGO_DB_PORT}:27017"
    volumes:
      - threads_mongo_data:/data/db
    networks:
      - WohaAI_dev_net
    profiles:
      - "repo"

  auth-redis-store:
    image: redis:7
    container_name: ${AUTH_SESSION_REDIS_HOST}
    ports:
      - "${AUTH_SESSION_STORE_PORT}:6379"
    command: >
      redis-server --requirepass "${AUTH_SESSION_STORE_PASSWORD}"
    restart: always
    networks:
      - WohaAI_dev_net
    volumes:
      - auth_redis_data:/data
    profiles:
      - "repo"

  memory-redis-store:
    image: redis:7
    container_name: ${AGENT_MEMORY_REDIS_HOST}
    ports:
      - "${AGENT_MEMORY_REDIS_PORT}:6379"
    command: >
      redis-server --requirepass "${AGENT_MEMORY_REDIS_PASSWORD}"
    restart: always
    networks:
      - WohaAI_dev_net
    volumes:
      - memory_redis_data:/data
    profiles:
      - "repo"

  threads-redis-store:
    image: redis:7
    container_name: ${THREADS_HISTORY_REDIS_HOST}
    ports:
      - "${THREADS_HISTORY_REDIS_PORT}:6379"
    command: >
      redis-server --requirepass "${THREADS_HISTORY_REDIS_PASSWORD}"
    restart: always
    networks:
      - WohaAI_dev_net
    volumes:
      - threads_redis_data:/data
    profiles:
      - "repo"


volumes:
  users_mongo_data:
  threads_mongo_data:

  memory_redis_data:
  threads_redis_data:
  auth_redis_data:
  
networks:
  WohaAI_dev_net: