services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  auth-kafka-broker:
    image: bitnami/kafka:3.6
    container_name: ${AUTH_MAILER_KAFKA_BROKER_HOST}
    ports:
      - "${AUTH_MAILER_KAFKA_BROKER_PORT}:${AUTH_MAILER_KAFKA_BROKER_PORT}"
    depends_on:
      - zookeeper
    environment:
      # Core
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${AUTH_MAILER_KAFKA_BROKER_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${AUTH_MAILER_KAFKA_BROKER_HOST}:${AUTH_MAILER_KAFKA_BROKER_PORT}

      # Single-node dev safe settings
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1

      # Auth env passthrough
      - KAFKA_CLIENT_USERS=${AUTH_MAILER_KAFKA_USERNAME}
      - KAFKA_CLIENT_PASSWORDS=${AUTH_MAILER_KAFKA_PASSWORD}

      # Allow plaintext
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - woahai_dev_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - auth-kafka-broker
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${AUTH_MAILER_KAFKA_BROKER_HOST}:${AUTH_MAILER_KAFKA_BROKER_PORT}