services:
  auth-kafka-broker:
    image: confluentinc/cp-kafka:7.5.3
    container_name: ${AUTH_KAFKA_BROKER_HOST}

    ports:
      - "${AUTH_KAFKA_BROKER_PORT}:${AUTH_KAFKA_BROKER_PORT}"

    environment:
      # KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      # =========================
      # Listeners
      # =========================
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:${AUTH_KAFKA_BROKER_PORT},CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${AUTH_KAFKA_BROKER_HOST}:${AUTH_KAFKA_BROKER_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # =========================
      # Single node dev settings
      # =========================
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # =========================
      # Dev safety
      # =========================
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    networks:
      - WohaAI_dev_net

  ## Kafka Topic Creator Container
  kafka-init-topics:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - auth-kafka-broker

    entrypoint: ["/bin/sh", "-c"]

    command: >
      "
      echo 'Waiting for Kafka...'
      cub kafka-ready -b ${AUTH_KAFKA_BROKER_HOST}:${AUTH_KAFKA_BROKER_PORT} 1 30

      echo 'Creating topics...'

      kafka-topics --create \
        --if-not-exists \
        --bootstrap-server ${AUTH_KAFKA_BROKER_HOST}:${AUTH_KAFKA_BROKER_PORT} \
        --topic ${AUTH_KAFKA_FORGOT_PASSWORD_EVENTS_TOPIC} \
        --partitions 1 \
        --replication-factor 1

      kafka-topics --create \
        --if-not-exists \
        --bootstrap-server ${AUTH_KAFKA_BROKER_HOST}:${AUTH_KAFKA_BROKER_PORT} \
        --topic ${AUTH_KAFKA_EMAIL_VERIFICATION_EVENTS_TOPIC} \
        --partitions 1 \
        --replication-factor 1

      echo 'Topics created successfully'
      "

    networks:
      - WohaAI_dev_net


networks:
  WohaAI_dev_net: