services:
  react_agent:
    build:
      context: ../../../services/agent/
      additional_contexts:
        packages: ../../../packages/
      dockerfile: Dockerfile
      target: development
    container_name: ${REACT_AGENT_CONTAINER_NAME}
    ports: 
      - "${REACT_AGENT_PORT}:${REACT_AGENT_PORT}"
    volumes:
      - ../../../services/agent/src:/app/src
    restart: always
    env_file:
      - ../../../.env
    networks:
      - woahai_dev_net


networks:
  woahai_dev_net:
    external: true