services:
  wohaai-agent:
    build:
      context: ../../
      dockerfile: agent/Dockerfile
      target: ${NODE_ENV}
    container_name: ${AGENT_CONTAINER_NAME}
    ports: 
      - "${AI_AGENT_PORT}:${AI_AGENT_PORT}"
    volumes:
      - ../../agent:/app/agent
    restart: always
    env_file:
      - ../../.env
    networks:
      - WohaAI_dev_net
    profiles:
      - "agentic"


networks:
  WohaAI_dev_net: