version: "3.9"

services:
  # ===========================
  # Users Postgres DB
  # ===========================
  users_postgres_db:
    image: postgres:16
    container_name: users_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERS_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: USERS_POSTGRES_DB_PASSWORD
      POSTGRES_DB: ${USERS_POSTGRES_DB_NAME}
    ports:
      - "${USERS_POSTGRES_DB_PORT}:${USERS_POSTGRES_DB_PORT}"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    networks:
      - woahai_network

  # ===========================
  # Threads Postgres DB
  # ===========================
  threads_postgres_db:
    image: postgres:16
    container_name: threads_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${THREADS_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${THREADS_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${THREADS_POSTGRES_DB_NAME}
    ports:
      - "${THREADS_POSTGRES_DB_PORT}:${THREADS_POSTGRES_DB_PORT}"
    volumes:
      - threads_postgres_data:/var/lib/postgresql/data
    networks:
      - woahai_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - microservices_net_01

volumes:
  users_postgres_data:
  threads_postgres_data:
  pgdata:

networks:
  woahai_network:
    driver: bridge
  woahai_agent_network:
    external: true
  microservices_net_01:
    external: true
