services:
  # ===========================
  # Users Postgres DB
  # ===========================
  users_postgres_db:
    image: postgres:16
    container_name: ${USERS_POSTGRES_DB_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${USERS_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${USERS_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${USERS_POSTGRES_DB_NAME}
    ports:
      - "${USERS_POSTGRES_DB_EXTERNAL_PORT}:${USERS_POSTGRES_DB_INTERNAL_PORT}"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    networks:
      - woahai_data_net
      - microservices_net

  # ===========================
  # Threads Postgres DB
  # ===========================
  threads_postgres_db:
    image: postgres:16
    container_name: ${THREADS_POSTGRES_DB_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${THREADS_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${THREADS_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${THREADS_POSTGRES_DB_NAME}
    ports:
      - "${THREADS_POSTGRES_DB_EXTERNAL_PORT}:${THREADS_POSTGRES_DB_INTERNAL_PORT}"
    volumes:
      - threads_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${THREADS_POSTGRES_DB_USER} -d ${THREADS_POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - data_net
      - microservices_net

  pgadmin_gui:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_gui
    restart: always
    depends_on:
      - ${USERS_POSTGRES_DB_HOST}
      - ${THREADS_POSTGRES_DB_HOST}
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
    - data_net
    - microservices_net

volumes:
  users_postgres_data:
  threads_postgres_data:
  pgdata:

networks:
  data_net:
    external: true

  microservices_net:
    external: true
