services:
  auth_redis_store:
    image: redis:7
    container_name: ${AUTH_REDIS_STORE_HOST}
    ports:
      - "${AUTH_REDIS_STORE_PORT}:${AUTH_REDIS_STORE_PORT}"
    command: >
      redis-server --requirepass "${AUTH_REDIS_STORE_PASSWORD}" --port ${AUTH_REDIS_STORE_PORT}
    restart: always
    networks:
      - microservices_net
      - data_net
    volumes:
      - auth_redis_data:/data

  memory_redis_store:
    image: redis:7
    container_name: ${MEMORY_REDIS_STORE_HOST}
    ports:
      - "${MEMORY_REDIS_STORE_PORT}:6379"
    command: >
      redis-server --requirepass "${MEMORY_REDIS_STORE_PASSWORD}" --port ${MEMORY_REDIS_STORE_PORT}
    restart: always
    networks:
      - microservices_net
      - data_net
    volumes:
      - memory_redis_data:/data

  threads_redis_store:
    image: redis:7
    container_name: ${THREADS_REDIS_STORE_HOST}
    ports:
      - "${THREADS_REDIS_STORE_PORT}:6379"
    command: >
      redis-server --requirepass "${THREADS_REDIS_STORE_PASSWORD}" --port ${THREADS_REDIS_STORE_PORT}
    restart: always
    networks:
      - microservices_net
      - data_net
    volumes:
      - threads_redis_data:/data

volumes:
  memory_redis_data:
  threads_redis_data:
  auth_redis_data:

networks:
  microservices_net:
    external: true

  data_net:
    external: true
