services:
  user_postgres_db:
    image: postgres:16
    container_name: user_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${USER_POSTGRES_PORT}:${USER_POSTGRES_PORT}"
    networks:
      - microservices_net_01

  chat_postgres:
    image: postgres:16
    container_name: chat_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${CHAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CHAT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CHAT_POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${CHAT_POSTGRES_PORT}:${CHAT_POSTGRES_PORT}"
    networks:
      - microservices_net_01
  agent_memory_store:
    image: qdrant/qdrant:latest
    container_name: agent_memory_store
    restart: always
    ports:
      - "${AGENT_MEMORY_STORE_PORT}:${AGENT_MEMORY_STORE_PORT}"
    networks:
      - microservices_net_01
  
  stm_vector_store:
    image: qdrant/qdrant:latest
    container_name: stm_vector_store
    restart: always
    ports:
      - "${STM_VECTOR_STORE_PORT}:${STM_VECTOR_STORE_PORT}"
    networks:
      - microservices_net_01

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - microservices_net_01

volumes:
  pgdata:

networks:
  microservices_net_01:
    external: true
