services:
    auth_mailer_queue:
      image: quay.io/fluvio/fluvio:latest
      container_name: auth_mailer_queue
      ports:
        - "${AUTH_FLUVIO_CONTROL_PANE_PORT}:${AUTH_FLUVIO_CONTROL_PANE_PORT}"
        - "${AUTH_FLUVIO_API_PORT}:${AUTH_FLUVIO_API_PORT}"
      environment:
        FLV_LOG: ${FLV_LOG}
      networks:
        - microservices_net


networks:
  microservices_net:
    external: true