services:
  memory_qdrant_store:
    image: qdrant/qdrant:latest
    container_name: memory_qdrant_store
    restart: always
    ports:
      - "${MEMORY_QDRANT_STORE_PORT}:${MEMORY_QDRANT_STORE_PORT}"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=${MEMORY_QDRANT_STORE_PORT}
    env_file:
      - ../../../.env
      - ../../../.env.docker
    networks:
      - microservices_net
      - woahai_data_net

networks:
  woahai_data_net:
    external: true
    
  microservices_net:
    external: true
