services:

  # captcha_verification_service:
  #   build:
  #     context: ../src/ms/captcha_verification_service/
  #     dockerfile: Dockerfile
  #     target: ${NODE_ENV}
  #   container_name: captcha_verification_service
  #   ports:
  #     - "${CAPTCHA_VERIFICATION_PORT}:${CAPTCHA_VERIFICATION_PORT}"
  #   volumes:
  #     - ../src/ms/captcha_verification_service/src:/app/src
  #   restart: always
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
  #     - CAPTCHA_VERIFICATION_PORT=${CAPTCHA_VERIFICATION_PORT}

  auth_mailer_service:
    build:
      context: ../../../src/ms/auth_mailer_service/
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: code_mailer_service
    ports:
      - "${AUTH_MAILER_SERVICE_PORT}:${AUTH_MAILER_SERVICE_PORT}"
    volumes:
      - ../../../src/ms/auth_mailer_service/src:/app/src
    restart: always
    depends_on:
      - redis_code_c
    env_file:
      - ../../../.env
      - ../../../.env.docker
    networks:
      - microservices_net_01

networks:
  microservices_net_01:
    external: true