services:
  auth-service:
    build:
      context: ../../../services/ms/auth_service/
      dockerfile: Dockerfile
      target: ${NODE_ENV}
      additional_contexts:
        packages: ../../../packages/
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    volumes:
      - ../../../services/ms/auth_service/src:/app/src
      - ../../../packages/:/app/packages
    restart: always
    env_file:
      - ../../../.env
      - ../../../.env.docker
    networks:
      - microservices_net

  user-service:
    build:
      context: ../../../services/ms/user_service/
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: user-service
    ports:
      - "${USERS_POSTGRES_DB_INTERNAL_PORT}:${USERS_POSTGRES_DB_EXTERNAL_PORT}"
    volumes:
      - ../../../services/ms/user_service/src:/app/src
    restart: always
    env_file:
      - ../../../.env
      - ../../../.env.docker
    networks:
      - microservices_net

  auth-mailer-service:
    build:
      context: ../../../services/ms/auth_mailer_service/
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: auth-mailer-service
    ports:
      - "${AUTH_MAILER_SERVICE_PORT}:${AUTH_MAILER_SERVICE_PORT}"
    volumes:
      - ../../../services/ms/auth_mailer_service/src:/app/src
    restart: always
    env_file:
      - ../../../.env
      - ../../../.env.docker
    networks:
      - microservices_net
    environment:
      - RUST_BACKTRACE=1

networks:
  microservices_net:
    external: true