version: "3.9"

services:
  code_mailer_service:
    build:
      context: ../src/microservices/code_mailer_service/service
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    container_name: code_mailer_service
    ports:
      - "${CODE_MAILER_PORT}:${CODE_MAILER_PORT}"
    volumes:
      - ../src/microservices/code_mailer_service/service:/src
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - REDIS_CODE_C=${REDIS_CODE_C}
      - REDIS_PASSWORD_CODE_C=${REDIS_PASSWORD_CODE_C}
      - CODE_MAILER_PORT=${CODE_MAILER_PORT}
    depends_on:
      - redis_code_c
    networks:
      - microservices_net_01

  captcha_service:
    build:
      context: ../src/microservices/captcha_service/service
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    container_name: captcha_service
    ports:
      - "${CAPTCHA_PORT}:${CAPTCHA_PORT}"
    volumes:
      - ../src/microservices/captcha_service/service:/src
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - CAPTCHA_PORT=${CAPTCHA_PORT}
    networks:
      - microservices_net_01

  user_verify_code_service:
    build:
      context: ../src/microservices/user_verify_code_service/service
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    container_name: user_verify_code_service
    ports:
      - "${USER_VERIFY_CODE_PORT}:${USER_VERIFY_CODE_PORT}"
    volumes:
      - ../src/microservices/user_verify_code_service/service:/src
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_CODE_C=${REDIS_CODE_C}
      - REDIS_PASSWORD_CODE_C=${REDIS_PASSWORD_CODE_C}
      - USER_VERIFY_CODE_PORT=${USER_VERIFY_CODE_PORT}
    depends_on:
      - redis_code_c
    networks:
      - microservices_net_01

networks:
  microservices_net_01:
    external: true
