version: "3.9"

services:
  api_gateway:
    build:
      context: ../src/microservices/api_gateway/service
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    container_name: api_gateway
    ports:
      - "${API_GATEWAY}:${API_GATEWAY}"
    volumes:
      - ../src/microservices/api_gateway/service:/src
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_GATEWAY=${API_GATEWAY}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - SIGNIN_SERVICE_PORT=${SIGNIN_SERVICE_PORT}
      - SIGNUP_SERVICE_PORT=${SIGNUP_SERVICE_PORT}
      - USER_VERIFY_CODE_PORT=${USER_VERIFY_CODE_PORT}
      - CODE_MAILER_PORT=${CODE_MAILER_PORT}
      - CAPTCHA_PORT=${CAPTCHA_PORT}
      - SIGNUP_VALIDATOR_PORT=${SIGNUP_VALIDATOR_PORT}
    networks:
      - microservices_net_01

networks:
  microservices_net_01:
    external: true
